// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgbxrrmnbwrbbclohvap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nYnhycm1uYndyYmJjbG9odmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzY0NTksImV4cCI6MjA2MDQ1MjQ1OX0.yrTsbLjkjhRFh799lXNvQ-rS5YC6hrEnaYkUt5ekoOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);